modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="alerts"
version="1.0.0"
displayName="Alerts"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="ilove, MCreator"

[[dependencies.alerts]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




